name: Ma super CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Node.js config
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Unit testing
        run: npm run test

      - name: App build
        run: npm run build

      - name: Build test
        run: ls -la ./dist

      - name: Dist folder upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Dist folder download
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Dist test
        run: ls-la .dist

      - name: Deploy on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
